apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: pkrgkowd9-java-quarkus
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-4a165467f2.jde2.p3.openshiftapps.com/rhtap/rhtap-qe:b1564d1588faf1a72ddf4125b4543313ca547186@sha256:31f81ed81d79a7cd7bda338eb9ac903eb8c1f4f5e9781fd96cfa0e11e1126697
        name: container-image  
